version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    restart: unless-stopped
    ports:
      - "100:80"
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      resume_ppl:
        ipv4_address: 192.168.105.2

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      resume_ppl:
        ipv4_address: 192.168.105.3

networks:
  resume_ppl:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.105.0/24

volumes:
  web_dataresume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/html'
